name: Publish Docker image

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build_and_push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set image tag
        run: rev=$(git rev-parse --short HEAD)

      - name: Build Docker image
        run: docker build . -t geralt

      - name: Push Docker image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          docker tag geralt 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2019-ecr-repo:$rev
          docker tag geralt 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2019-ecr-repo:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2019-ecr-repo:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2019-ecr-repo:latest

  build_only:
    name: Build Docker image only
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t geralt






