name: AWS Deploy

on:
  push:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./kjell

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: aws s3 ls
      - run: sam build --use-container
      - name: check if branch is main
        if: github.ref == 'refs/heads/main'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-5150 --s3-bucket pgr301-sam-bucket --capabilities CAPABILITY_IAM --region eu-west-1